### ISSUE TITLE
example_echosvr.cpp readwrite_routine函数 

### ISSUE THREAD

**Issue by Azure1029** [Tencent/libco#101]
对于read的返回值小于等于0应该分为两种情况考虑
1 如果客户端断开了连接 则read返回的是-1  此时应该关闭连接
2 如果客户端没有断开连接 只是没有发数据 则read返回的是0 errno=EAGAIN 此时不关闭
示例代码没有对1做处理 如果客户端断开连接 会导致服务端某个协程一直被这个断开的连接占用 造成连接和协程的泄露。
求作者解惑

**Comment by wechatsunny** [comment]
是的，example有问题，已修改，谢谢。
