### ISSUE TITLE
请问为什么hook的函数中每次判断sys func是否被设置

### ISSUE THREAD

**Issue by xinnjie** [Tencent/libco#102]
比如`close`中

    int close(int fd)
    {
	    HOOK_SYS_FUNC( close );
	    if( !co_is_enable_sys_hook() )
	    {
		   return g_sys_close_func( fd );
	    }
	    free_by_fd( fd );
	    int ret = g_sys_close_func(fd);
	   return ret;
    }

`HOOK_SYS_FUNC`每次都会检查`g_sys_close_func`，但是`g_sys_close_func`作为static变量，早就已经初始化好了。是有更深层次的原因吗？
@leiffyli

**Comment by leiffyli** [comment]
static全局变量的初始化依赖于系统加载顺序，有可能函数被调早于static变量的初始化，因此这里加了动态判断全局g_sys_close_func是否已经初始化。

**Comment by xinnjie** [comment]
虽然全局变量初始化经常会出问题，但是据我所知，像这种同一个cpp文件（编译单元）里初始化，并且这些全局变量之间还没有依赖关系，一般初始化是没有问题的。

我在网上也查到，标准里对这种static全局变量的初始化（准确得说是dynamic initialization），是有保证初始化在同一个编译单元里的函数调用之前的。

> It is implementation-defined whether or not the dynamic initialization (8.5, 9.4, 12.1, 12.6.1) of an object of namespace scope with static storage duration is done before the first statement of main. If the initialization is deferred to some point in time after the first statement of main, it shall occur **before the first use of any function or object defined in the same translation** unit as the object to be initialized.

（抱歉，可能有些过于追究了，本身只是语言上的细节问题而已。）如果之前没加判断却出了未初始化的问题，请务必告诉我（了却我的好奇心）。（另外像这种虽然标准有说，但是编译器没有实现的事情其实也正常）
十分感谢大大 @leiffyli

**Comment by leiffyli** [comment]
是的。系统会保证在main执行之前，依次初始化各个cpp文件里面的全局变量或者执行 attribute (constructor) 定义的初始化函数。

这里可能的场景是在加载全局变量之前的一些系统调用，比如read调用，因为静态编译的原因，他会直接跳转到我们hook后的read函数，这种情况全局的系统read地址是还没有加载的。

**Comment by xinnjie** [comment]
wow，我按照描述复现出来了。
假如在其他全局变量初始化时用到hook过的read，这时系统read地址是还没有加载的。
谢谢大大 @leiffyli
