### ISSUE TITLE
协程的另外一种实现方式

### ISSUE THREAD

**Issue by xiaoliang314** [Tencent/libco#111]
我是来借助大名鼎鼎的libco人气，推广我的一个项目[github.com/xiaoliang314/libatask](https://github.com/xiaoliang314/libatask)。不好意思打扰各位了。<br/>
&nbsp;&nbsp;&nbsp;&nbsp;为了解决I/O密集型与事物密集型程序的性能问题，大家都从同步方式转变到异步了。异步的核心就是基于事件和回调的。而异步最让人头疼的地方在于它将上下文信息和执行逻辑给完全分离。使用回调的方式，上下文信息的恢复难度还不算大（通过事件携带私有参数的方式可以做到），而执行逻辑的恢复难度则可以上天。比如，你的代码一个for里面被异步拆分成了两半。你想在回调函数里面再恢复这个逻辑是非常非常的困难，更何况外面可能还嵌套了if，或者另一个for。就算你恢复了这个逻辑，但是这两段代码早已面目全非，可读性非常的糟糕。<br/>
&nbsp;&nbsp;&nbsp;&nbsp;为了恢复执行逻辑，或者要求再低些，让执行逻辑更容易维护。有人使用了状态机系列方式，有人改造业务逻辑适应。当然还有最方便的协程。协程有着优秀的异步执行逻辑恢复能力。协程一般都是一些高级的语言高级的原生的功能，像C/C++这种古老的底层语言似乎没戏。然而任由其他语言功能如何变化，C/C++却拥有其他语言没有的语法糖神器 一一 宏！以及内嵌汇编的功能。因此许多优秀的人实现了这个功能并开源了，但他们实现的方式也是各不相同。libco作为热度非常高的协程库，同时经过了很多年而且规模庞大的用户群体验证，实力不容怀疑。不过，libco资源消耗（栈的内存占用，上下文恢复的cpu消耗）和跨平台（支持的cpu种类有限）也是大家拿去优化和改进的地方，比如改进版的libaco也将libco的问题进行了解决和优化，达到了一个非常好的效果。<br/>
&nbsp;&nbsp;&nbsp;&nbsp;现有的大部分协程实现都是通过汇编或者setjump以及ucontext等切换堆栈做的，一部分使用宏嵌套lambda表达式通过捕获变量来做。还有一些另类的做法是抛弃栈空间（如：protothread)，依靠C语言的switch和其他结构化语句可嵌套的方式，用宏包装之后实现了执行逻辑的恢复。可以说，使用纯C/C++来实现的方式，在跨平台跨cpu性和性能上都非常的高。缺点是，上下文信息难以恢复，以及不支持调用子协程。<br/>
&nbsp;&nbsp;&nbsp;&nbsp;libatask也使用纯C实现的协程，改进了switch方式，采用switch-goto方式实现。使用一个字节的来恢复执行逻辑。同时支持switch的case里面进行yield，而protothread是不能跳转到switch的case分支里的。
&nbsp;&nbsp;&nbsp;&nbsp;相对于切换堆栈以及lambda表达式方式来说，libatask则完美结合事件机制，同时通过事件携带的task信息支持了上下文信息的恢复。实现堆栈的零拷贝。并且它还支持任意多的事件同时驱动，比如，我可以在开启I/O事件的同时又开启timer以及更多的其他事件，并等待任意一个事件的到来。并在协程任务中对事件源进行判断和处理以实现I/O超时。
&nbsp;&nbsp;&nbsp;&nbsp;libatask还支持调用子协程并在子协程中可以进行yield，待子协程结束后再返回父协程。同时，协程和子协程在第一次调用时可以像普通函数一样传递任意类型和数量的参数。同时，任意一个协程都是可重入的，只要为它提供一个task结构即可。
&nbsp;&nbsp;&nbsp;&nbsp;libatask可以方便地确定堆栈大小，避免内存浪费。
&nbsp;&nbsp;&nbsp;&nbsp;libatask不存在任何平台兼容性问题，核心功能仅需要一个支持C89或者ANSI C编译器即可，全部功能仅还需再支持__VA_ARGS__宏，同时库资源占用非常小（32位ARM MCU环境：RAM 56B，CODE 700B）也很适用与嵌入式和单片机开发中。<br/>
&nbsp;&nbsp;&nbsp;&nbsp;除此之外，libatask还集成了一些实用的宏，以及一个很好用的单向循环链表，支持slist_foreach_等系列遍历操作，遍历中节点安全插入和删除功能。同时支持判断节点是否被删除，可以防止节点重复插入与重复删除。slist简单且高性能，同时还有基于slist实现的lifo及fifo。
&nbsp;&nbsp;&nbsp;&nbsp;libatask采用MIT许可，推广并非为了盈利。希望给大家更多的一些选择，同时也希望自己的成果能产生更多的价值。

**Comment by heiher** [comment]
学习了，看下来相当于在函数内维护了一个状态机，yield即更新状态记录离开的位置标号，然后退出当前函数回到调度。调度选择其它任务并根据其状态记录重入之前的位置标号。但因为yield过程中栈空间复用了，所以其数据可能被破坏，因此局部变量需要在yield前后备份和恢复。

感觉在栈处理上与共享型拷贝栈的思路类似，只是一个是任务系统实现，对用户“透明”（栈空间解引用有风险），这个是要用户自行维护。而在调度切换上，开销相对setjmp/longjmp高一些吧。

**Comment by xiaoliang314** [comment]
@heiher 嗯，这里有两个问题我回答一下
> 局部变量需要在yield前后备份和恢复

有需要在yield之后使用的局部变量，应该放在task提供的栈中，通过vars->var_name 直接使用，没有备份和恢复的过程。
> 而在调度切换上，开销相对setjmp/longjmp高一些吧。

使用事件调度的切换确实比setjmp/longjmp效率低一些，但是，这是为了防止递归重入问题和保证事件优先级而设计的。libatask提供了直接调用的事件的方式el_event_sync_post，使用el_event_sync_post恢复协程的效率比setjmp/longmp更高。
我举个我遇到的递归重入的例子：<br/>
例1： 
   假如协程A执行了一个I/O操作，它的代码可能如下：
```
协程A:
    io_read(arg1, arg2, on_read);
    yield();

on_read:
   resume(A);
```
如果io_read中由于当前I/O已经发生错误，直接触发on_read(err)，那这样将会导致在io_read中调用on_read再调用resume(A)，此时，因为A当前并未执行到yield导致on_read中无法正常resume A。A在io_read完成之后(on_read已经触发)，才执行yield，但此时却已经无法再被唤醒。<br/>
例2： 
    假如我有一个I/O类有两个方法close、open。我使用了一个is_open标识当前I/O的状态。同时在close注册了一个监听器on_close。那么close、open以及on_close的方法可能实现如下：<br/>
```
   close:
         /* 执行I/O关闭的一些资源回收操作 */
        ...
        /* 通知I/O被关闭 */
        this->on_close();
        this->is_open = false;
  
   open:
        /* 打开I/O */
        ...
        this->is_open = true;

    on_close:
        /* 尝试打开I/O */
        io->open();
```
此时，由于this->on_close()时间接调用到了类的其他方法(open)或者自身(close)，在close执行过程中改变了当前执行环境的数据，最后的结果是，内部状态不一致。I/O打开了，但是is_open为false，这种情况和幽灵的多线程是差不多的，而且这种方式还不能像多线程那样加锁来解决<br/>
采用事件循环则可以避免由事件回调引发的递归重入问题。它总是等待一个函数执行完成后，才会执行下一个事件处理函数。

**Comment by heiher** [comment]
> @heiher 嗯，这里有两个问题我回答一下
> 
> > 局部变量需要在yield前后备份和恢复
> 
> 有需要在yield之后使用的局部变量，应该放在task提供的栈中，通过vars->var_name 直接使用，没有备份和恢复的过程。
> 
> > 而在调度切换上，开销相对setjmp/longjmp高一些吧。
> 
> 使用事件调度的切换确实比setjmp/longjmp效率低一些，但是，这是为了防止递归重入问题和保证事件优先级而设计的。libatask提供了直接调用的事件的方式el_event_sync_post，使用el_event_sync_post恢复协程的效率比setjmp/longmp更高。
> 我举个我遇到的递归重入的例子：
> 
> 例1：
> 假如协程A执行了一个I/O操作，它的代码可能如下：
> 
> ```
> 协程A:
>     io_read(arg1, arg2, on_read);
>     yield();
> 
> on_read:
>    resume(A);
> ```
> 
> 如果io_read中由于当前I/O已经发生错误，直接触发on_read(err)，那这样将会导致在io_read中调用on_read再调用resume(A)，此时，因为A当前并未执行到yield导致on_read中无法正常resume A。A在io_read完成之后(on_read已经触发)，才执行yield，但此时却已经无法再被唤醒。

我不是特别能理解这样组合使用协程的阻塞同步模式与非阻塞的异步模式有什么好处？如果非要在协程上再跑事件循环，不应该是这样最简单吗？（其实用协程不更多的应该是切换到同步I/O接口的思维模式上吗）

协程A:
    for (;;) {
        // 协程版的 _poll 内部非阻塞的调用poll，若无事件ready，则yield来调度切换其它协程。
        // 将来协程A再被执行时，是yield方法返回到_poll继续执行。
        _poll();
        // 处理事件
        for (...) {
            cb(...);
        }
    }

> 
> 例2：
> 假如我有一个I/O类有两个方法close、open。我使用了一个is_open标识当前I/O的状态。同时在close注册了一个监听器on_close。那么close、open以及on_close的方法可能实现如下：
> 
> ```
>    close:
>          /* 执行I/O关闭的一些资源回收操作 */
>         ...
>         /* 通知I/O被关闭 */
>         this->on_close();
>         this->is_open = false;
>   
>    open:
>         /* 打开I/O */
>         ...
>         this->is_open = true;
> 
>     on_close:
>         /* 尝试打开I/O */
>         io->open();
> ```
> 
> 此时，由于this->on_close()时间接调用到了类的其他方法(open)或者自身(close)，在close执行过程中改变了当前执行环境的数据，最后的结果是，内部状态不一致。I/O打开了，但是is_open为false，这种情况和幽灵的多线程是差不多的，而且这种方式还不能像多线程那样加锁来解决
> 
> 采用事件循环则可以避免由事件回调引发的递归重入问题。它总是等待一个函数执行完成后，才会执行下一个事件处理函数。

更不理解了，为什么on_close通知回调中中会有需求再调用相同对象的open方法？

**Comment by xiaoliang314** [comment]
@heiher 
> 我不是特别能理解这样组合使用协程的阻塞同步模式与非阻塞的异步模式有什么好处？如果非要在协程上再跑事件循环，不应该是这样最简单吗？（其实用协程不更多的应该是切换到同步I/O接口的思维模式上吗）
协程A:
for (;;) {
// 协程版的 _poll 内部非阻塞的调用poll，若无事件ready，则yield来调度切换其它协程。
// 将来协程A再被执行时，是yield方法返回到_poll继续执行。
_poll();
// 处理事件
for (...) {
cb(...);
}
}

协程跟异步事件结合更好。 
理由： 
1、现有的网络库都是采用异步I/O+事件的方式驱动的
2、游戏开发中也全是事件
3、用事件驱动的协程能更好跟现有的异步I/O库结合
4、hook原生API将I/O变同步的方式，不支持多路等待。而事件就可以

> 更不理解了，为什么on_close通知回调中中会有需求再调用相同对象的open方法？

open、close举例确实不合理，名字没取对。把open、close换成普通方法A、B更好。<br/>
这里主要说明的一个问题，类的方法递归嵌套调用会发生 A -> ... -> B这种情况，它会A执行过程中改变A的执行环境数据，造成对象的内部状态不一致的情况。

**Comment by xiaoliang314** [comment]
@heiher 
> 如果非要在协程上再跑事件循环，不应该是这样最简单吗？

我有点理解你说的意思了，你是说我的协程上跑了一个事件循环吗？<br/>
这里我说明一下：
libatask的协程不同于有栈协程，在libatask的协程上是不能跑事件循环的，事件循环是跑在主线程中。 
libatask的协程其实是一个特殊的函数。它靠事件驱动，它是**事件的回调函数。**
每次协程恢复（回调）都会传入两个参数：
1、task对象 
2、当前的事件(event) 
**task**：在task中有一个1Byte的状态变量，记录上一次return的位置，并通过这个变量goto到return之后的地方。因为goto非常的强大，所以，它才能实现协程（goto能跳转到任何结构语句的内部）。 
task除了携带当前的状态变量外，还有指向协程的异步变量地址的指针，每次函数开头都将这个地址赋给vars，直接通过vars使用这些异步变量。task的实现存在很多细节，就不细说了。 
**event**：也是非常重要，它在多事件同时驱动的情况下起到分辨当前触发的事件的作用。 
 
总的来说，libatask协程的目标是管理多事件回调将所有异步操作同步化（CPS），更直观地异步编程。 
 
以机器人做一系列动作说明它的用处： 
比如机器人需要跳n下，转一圈，再打招呼，那么实现如下： 
```
void do_action(task_t *task, event_t *ev, int n)
{
    uint8_t *bpd = TASK_BPD(task);
    /* 声明以及获取协程异步变量 */
    struct vars
    {
         action_event_t action_ev;
         int i;
         int n;
    } *vars = (struct vars *)task_asyn_vars_get(task, sizeof(*vars));

    /* 协程开始 */
    bpd_begin(4);

     /* 事件初始化 */
     event_init_inhert(&vars->action_ev.event, &task->event);
    /* 再yield之前将用到的参数记录到异步变量中 */
    vars->n = n;
     
     /* 跳n下 */
     for (vars->i = 0; vars->i < vars->n; vars->i++)
     {
          jump(&vars->action_ev);
          bpd_yield(1);
          
          /* 摔倒，则爬起来 */
          if (vars->action_ev.err == FALL_DOWN)
          {
               stand_up(&vars->action_ev);
               bpd_yield(2);
          }
     }
     /* 转一圈 */
     rotate(&vars->action_ev);
     bpd_yield(3);
     /* 打招呼 */
     wave_hand(&vars->action_ev);
     bpd_yield(4);

    /* 协程结束 */
    bpd_end();
    /* 异步返回，返回父协程 */
    task_asyn_return(task);
}
```
其他地方只需要使用task_start或者异步调用do_action即可完成这样一个异步流程。 

   task_start方式：
```
   /* 启动跳3下转圈协程 */
   task_start(task, do_action, 3);
```
父协程异步调用方式：
```
   /* 1是和bpd_yield的数字一个意思，协程的断点号 */
   task_bpd_asyn_call(1, task, do_action, 3);
```

**Comment by heiher** [comment]
@xiaoliang314 

基本清楚了，优势即是传统协程设计向上提供阻塞的同步接口，这样的接口通常不向上传递触发的多个events，所以在一个协程内处理I/O多路复用相对麻烦。

该设计与传统的事件循环比较，相同之处是事件驱动Task执行，上下文数据外带（数据不能持久存储在栈中）；不同之处是传统的事件驱动要将业务逻辑分解成多个独立的回调，每执行一个回调后滑动到下一个回调，从代码上来看业务逻辑被分解成多个碎片，而该设计虽然同样是外带数据，但允许将业务整体写在一个函数中，调度后重入时通过状态记录跳过已执行的代码片断。

感谢解释。

**Comment by xiaoliang314** [comment]
@heiher 不客气，有栈协程也有自己的优势。 
1、有栈线程可以hook API变同步，hook住API之后，可以直接调用I/O阻塞的第三方库，用法比肩线程。同时，在单线程并发时，不用考虑并行的数据竞争，无锁，协程数量也比普通线程高得很多。 
2、用法比libatask更简单 

HevTaskSystem的任务栈解决内存消耗的思路也很好

**Comment by opt-liang** [comment]
https://github.com/idealvin/coost.git

跨平台类go语言编程的c++协程库。
