### ISSUE TITLE
coctx_swap.S存在缺陷bug，导致不可预期后果或者core dump

### ISSUE THREAD

**Issue by wall2in** [Tencent/libco#128]
最近看了一下项目，发现[https://github.com/Tencent/libco/blob/master/coctx_swap.S](url)
存在缺陷，不幸运的情况下，会导致程序安静的以错误方式运行，幸运的话会导致程序crash并且core dump。

因为coctx_swap.S部分的代码并没有考虑到ASLR，

拿line 56行开始的x86_64举例子：

`line 57:   leaq 8(%rsp),%rax`

因为ASLR，即使是函数调用也会出现，因此，rsp寄存器加上8后，不一定就是父函数的在push返回地址前的栈顶，可能产生的栈状况如下：

`^high addr|<--caller's stack-->|<--random stack that not used-->|<--callee's stack-->|^low addr`

因此：

`line 64:   pushq -8(%rax) //ret func addr`

 此处的代码，保存的就不一定是调用coctx_swap后的返回地址保存的地方，如果这个错误地址在后续的栈切换后，很不幸的能够恰好跳转到一段可执行的代码处，程序或许会以错误的方式悄悄的运行一段时间。

希望可以提供新的版本修复

小白愚见，如果不对麻烦指正

**Comment by hnwyllmm** [comment]
函数调用与ASLR无关。参考intel手册对CALL指令的解释。简单的说，call相当于：
```
push rip
rip = new function address
```
所以call对栈的修改就是 push rip, 减了8字节

**Comment by kaiywen** [comment]
ASLR 只影响基址，不影响调用栈布局，不会影响函数调用

**Comment by wall2in** [comment]
了解不够，谢谢指正，我回去再详细看资料
