### ISSUE TITLE
我发现co_hook_sys_call.cpp里面对connect的hook没有使用poll去等待异步结果，导致一些第三方库connect时失败

### ISSUE THREAD

**Issue by zhubenwuzui** [Tencent/libco#13]
因为很多第三方库（比如hiredis或者mysql c driver） 创建连接时使用的是同步connect的函数， 接入libco后，mysql c driver 调用 mysql_real_connect 会返回115错误，调试发现当调用到hook的connect函数后，直接返回ret -1， errno为115。
我觉得这里是不是应该模拟同步connect时的ret， 即发起连接请求后立即调用co_poll yield出去，等待connect成功后再回到这里返回正确的ret。
现在的实现导致mysql c driver无法正确连接成功。

**Comment by zhubenwuzui** [comment]
刚看了一下发现十几天前已经更新这里的代码了。我用新代码再试一下。

**Comment by zhubenwuzui** [comment]
tencent-wechat的那个git 库的connect代码是错的。。。

**Comment by leiffyli** [comment]
嗯？tencent-wechat的代码和这边是一起同步的，能具体描述下问题么？

**Comment by zhubenwuzui** [comment]
@leiffyli 你对比一下 tencent-wechat的 co_hook_sys_call.cpp 里面的connect函数就知道啦

**Comment by leiffyli** [comment]
@zhubenwuzui 额，我这边看到的是一致的呀，你再看下是否是最新的

**Comment by zhubenwuzui** [comment]
@leiffyli 难道是中午没睡觉产生幻觉了。。。
应该是之前我本地库没有git pull吧。总之现在两边都对了。
多谢回复！

**Comment by leiffyli** [comment]
@zhubenwuzui ok，欢迎继续交流：）
