### ISSUE TITLE
LICENSE issue.

### ISSUE THREAD

**Issue by winlinvip** [Tencent/libco#134]
很感谢微信开源了libco，我是流媒体直播服务器[SRS](https://github.com/ossrs/srs)的维护者，SRS是MIT的LICENSE，SRS用的是之前的coroutine库[ST/StateThreads](https://github.com/ossrs/state-threads)。

ST是MPL或GPLv2的LICENSE，据说好像可以用so的方式使用但由于MPL太古老也少见，所以不能确定这个LICENSE是否可用，所以准备换coroutine库，就在考虑libco了。

> The State Threads library is a derivative of the Netscape Portable Runtime library (NSPR) and therefore is distributed under the Mozilla Public License (MPL) version 1.1 or the GNU General Public License (GPL) version 2 or later.

我看libco(2013年)是Apache的LICENSE，但是另外一个2011年的项目也有[bsnes/libco](https://github.com/byuu/bsnes/blob/master/libco/libco.h)协议是ISC。

[![image](https://user-images.githubusercontent.com/2777660/72120318-8baf8880-3392-11ea-889e-f94cdded43f0.png)](https://www.jianshu.com/p/86251523e898)

我的问题是：
1. 是否 wechat/libco，是从 bsnes/libco fork的呢？
1. 按上图所说， bsnes/libco ISC协议，是否能转成 wechat/libco Apache协议没有问题？

希望能解答我的疑惑。

**Comment by zsinba** [comment]
mark

**Comment by bb010g** [comment]
bump

**Comment by winlinvip** [comment]
计划改善SRS依赖的协程库[state-threads](https://github.com/ossrs/state-threads)，MPL协议可以商用而且不影响MIT的SRS，另外协程库太老了支持了很多没用的OS，性能上做优化也不太方便。
