### ISSUE TITLE
问一下libco开发有没有什么受控环境，统一环境的开发指南。

### ISSUE THREAD

**Issue by helintongh** [Tencent/libco#137]
libco采取hook api方式，导致他会劫持控制流唉，如果同步一个api直接就变成异步api。这样用在项目里很危险想问一问有没有使用这个库的一些约定规避掉一些错误。

**Comment by helintongh** [comment]
libco不太可复用，采取的是stackless的方式。

**Comment by opt-liang** [comment]
https://github.com/idealvin/coost.git

跨平台类go语言编程的c++协程库。
