### ISSUE TITLE
协程调度是抢占式的吗？

### ISSUE THREAD

**Issue by legendtkl** [Tencent/libco#14]
既然 coroutine 是用户态的，那么就有个问题：coroutine 调度是抢占式的吗？

谢谢！

**Comment by wechatsunny** [comment]
不是，libco的调度完全依靠事件驱动

发件人: legendtkl [mailto:notifications@github.com]
发送时间: 2017年1月5日 15:25
收件人: Tencent/libco
抄送: Subscribed
主题: [Tencent/libco] 协程调度是抢占式的吗？ (#14)


既然 coroutine 是用户态的，那么就有个问题：coroutine 调度是抢占式的吗？

谢谢！

**Comment by legendtkl** [comment]
好的，谢谢！
