### ISSUE TITLE
请问libco特性怎么支持mysqlclient？

### ISSUE THREAD

**Issue by liaobinxu** [Tencent/libco#17]
README介绍：
libco 支持gethostbyname、mysqlclient、ssl等常用第三库(New) , 是怎么支持的？ 有通过libco修改后mysqlclient的吗？

**Comment by wechatsunny** [comment]
Mysqlcli,ssl底层都要调用socket的一些connect/read/write方法，libco  hook了这些方法，所以直接就支持了
Gethostbyname稍微复杂一点，但是libco也hook了相应的方法，所以支持了

发件人: liaobinxu [mailto:notifications@github.com]
发送时间: 2017年2月3日 17:38
收件人: Tencent/libco
抄送: Subscribed
主题: [Tencent/libco] 请问libco特性怎么支持mysqlclient？ (#17)


README介绍：
libco 支持gethostbyname、mysqlclient、ssl等常用第三库(New) , 是怎么支持的？ 有通过libco修改后mysqlclient的吗？

**Comment by liaobinxu** [comment]
对不起，忘了及时回复了。请问修改后的mysqlclient和gethostbyname能开源吗？

**Comment by leiffyli** [comment]
@liaobinxu mysqlclient在默认的hook实现里面已经是支持的了，没有特殊的定制代码。GetHostByName这个接口的话，可以看下co_hook_sys_call.cpp这个文件里面的实现。
欢迎继续交流：）

**Comment by liaobinxu** [comment]
谢谢，有其他问题，再请教
