### ISSUE TITLE
跨平台协程库

### ISSUE THREAD

**Issue by opt-liang** [Tencent/libco#197]
https://github.com/idealvin/coost.git

支持arm、x86、amd64架构
支持linux、window、mac系统。

**Comment by opt-liang** [comment]
推荐使用。

**Comment by hnwyllmm** [comment]
到处在别人门口拉屎合适吗

**Comment by opt-liang** [comment]
嗯，你说的对，放心我不会拉你头上的。

**Comment by AlongsCode** [comment]
能把这个库平台扩展到windows吗，毕竟工业级的轻量协程还是比较信任腾讯的水平的
