### ISSUE TITLE
need more document

### ISSUE THREAD

**Issue by Baz2013** [Tencent/libco#2]
能给出一些详细点的使用文档吗

**Comment by skyformat99** [comment]
我也希望有一些详细点的使用文档

**Comment by wechatsunny** [comment]
代码库里面有几个example，常见的使用（svr/cli/poll 等）方法包含在里面了，我们可以考虑更详细的使用文档，能否列举一些例子？

**Comment by ovmarschen** [comment]
确实新手的话不仔细看代码不太容易看懂，Sample没有注释不知道怎么用

**Comment by ovmarschen** [comment]
诚招文档作者，质量可以的合入
此外我们可以提供些新版公仔

**Comment by taozhijiang** [comment]
小白写了一个，敬请拍砖。
[《腾讯libco协程库学习笔记》](https://taozj.org/2016/11/%E8%85%BE%E8%AE%AFlibco%E5%8D%8F%E7%A8%8B%E5%BA%93%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/)

还有tencent-wechat账号也维护了一个版本，那里提出的issue和PR都没人应对，是不是那个repo没人维护啊？
