### ISSUE TITLE
co_poll_inner函数有个异常情况需要处理

### ISSUE THREAD

**Issue by lichuang** [Tencent/libco#46]
在AddTimeout出错的情况下，应该把前面已经加入到epoll的fd删除掉，否则这里返回了，而epoll调用回来的时候指针已经是野指针了。尽管AddTimeout出错的情况比较罕见，但是我确实是碰到了。

**Comment by leiffyli** [comment]
@lichuang lichuang你好，这个问题确实是存在的。稍后我会更新一个版本，包含以下几个点：
1、AddTimeout失败后未删除epoll fd的bug修复
2、超时时间支持无限超时；
      当前系统最大超时为40s，过大的超时时间会被对齐到40s。更新后可以支持无限大的超时时间。
