### ISSUE TITLE
如何在协程中添加锁的机制？

### ISSUE THREAD

**Issue by youzp** [Tencent/libco#66]
很多情况下需要对全局变量进行加锁操作，如果原有代码中使用到了pthread_mutex锁机制，这种情况下如何进行协程锁的替换呢？

**Comment by wechatsunny** [comment]
加锁有两种情况

1.       对一个简单数据结构的读写，耗时很短本身就不需要用到协程的等待机制，也就是直接 lock 读/写 unlock就可以了

2.       加锁后需要做网络操作，那么此时是需要协程兼容的“锁” 来解决的


协程的使用可以认为是用非常自然的代码来实现异步代码里面的状态机功能

多个线程，每个线程开了很多协程，就等于每个线程有很多的异步状态机在跑

发件人: Vincent You [mailto:notifications@github.com]
发送时间: 2017年12月28日 17:01
收件人: Tencent/libco
抄送: Subscribed
主题: [Tencent/libco] 如何在协程中添加锁的机制？ (#66)


很多情况下需要对全局变量进行加锁操作，如果原有代码中使用到了pthread_mutex锁机制，这种情况下如何进行协程锁的替换呢？
