### ISSUE TITLE
阻塞read最终还是会阻塞?

### ISSUE THREAD

**Issue by yuling3437** [Tencent/libco#77]
int timeout = ( lp->read_timeout.tv_sec * 1000 ) 
				+ ( lp->read_timeout.tv_usec / 1000 );

	struct pollfd pf = { 0 };
	pf.fd = fd;
	pf.events = ( POLLIN | POLLERR | POLLHUP );

	int pollret = poll( &pf,1,timeout );

	ssize_t readret = g_sys_read_func( fd,(char*)buf ,nbyte );

poll 超时之后 最终还是在g_sys_read_func这句阻塞了整个线程??  还是说有什么要注意的呢?

**Comment by YingshuLu** [comment]
不会阻塞， 此时的fd是non-blocking.

**Comment by yuling3437** [comment]
了解了,我一开始假设使用的是阻塞的fd
