### ISSUE TITLE
协程共享栈的问题

### ISSUE THREAD

**Issue by messi824** [Tencent/libco#8]
看了源码和这篇文章[《揭秘：微信是如何用libco支撑8亿用户的》](http://dev.qq.com/topic/58203cfcd149ba305c5ccf85)，对共享栈那里有点不能理解啊！
尤其这里“libco也提供了stackless的协程共享栈模式，可以设置若干个协程共享同一个运行栈。”，谁能结合代码讲一下？co_swap就行

**Comment by messi824** [comment]
看了一下午代码，感觉应该是这样的：共享栈是在多个线程或者进程之间共享的。同一个线程之内应该是不能共享的，同一个线程之内的协程都有各自的栈，同一个线程内切换的时候需要做复制操作；不同线程之间可以共享某个堆栈，如果在线程间的协程切换时需要进行复制操作。不知道理解的是否正确，欢迎大家讨论

**Comment by messi824** [comment]
看代码终于明白了。以example_copustack.cpp为例，它在一个线程中分配了128个栈，则128*n(n>=0)号协程都使用0号栈，128*n+1使用1号栈，以此类推。
当协程运行时，运行到co_swap，如果0号协程是第一次使用pending_co->stack_mem->ocupy_co，则其为null，此时将pending_co赋值给它；如果第二次128号协程过来运行，判断出这个变量其实保存的是0号协程的内容，此时，需要执行copy操作，把0号协程的栈信息保存到malloc的空间。
感觉这样并不能节省多少空间啊。。。虽然运行栈的空间变小了，但是新赠了额外保存协程信息的内存，会不会得不偿失啊？

**Comment by willkozheng** [comment]
这个优化点，主要在于，栈的内存峰值不一定是栈切换时发生的。
例如，
栈a的内存峰值为8k，发生切换时只需使用4k，那使用共享的可以节约4k。

**Comment by messi824** [comment]
这个感觉优化有限，因为并不能控制一定在4k的时候切换，如果切换的时候就是8k，那不是还浪费了8k的空间存储？

**Comment by willkozheng** [comment]
1.不会存在浪费
2.是否能节省，取决于切换时是否峰值。正常来说，一个协程不可能每次切换都处于峰值。
这个是针对场景性的优化，当然不能保证每份代码都起作用，但是越复杂的逻辑这个效果会越明显。

**Comment by messi824** [comment]
学习了，非常感谢！

**Comment by wechatsunny** [comment]
close
