### ISSUE TITLE
协程任务栈技术交流

### ISSUE THREAD

**Issue by heiher** [Tencent/libco#80]
Hi,

在实现一个独立栈的协程，之所以没有使用共享栈，主要还是优先考虑的切换开销，不过实现中允许协程任务创建时指定栈大小，不必每个任务相同大小，一定程度上缓解浪费吧。但是，如果估算太小，当然是有栈溢出的风险的。

那么，到底有没有既能不浪费内存，又能减少切换开销的栈解决方法呢？

代码仓库：https://github.com/heiher/hev-task-system

**Comment by heiher** [comment]
任务栈特点：
1. 任务栈一旦被使用，其绝对地址不可改变，因为栈中存储的指针可能引用栈空间。
2. 多数情况下对栈空间的需求是较小的，但存在突发情况，所以分析少了可能溢出，分配多了浪费。

共享内存栈：
1. 节约内存资源，所有任务共享同一个栈内存。
2. 增加切换开销，每个任务切换时，都需要备份当前任务已使用的栈，恢复新任务栈。

独立内存栈：
1. 浪费内存资源，所有任务都需要分配满足上限的栈空间，但一个线程同一时刻只有一个协程在运行。
2. 减少切换开销，每个任务切换时，相对共享内存栈，只需要调整栈指针。

基于栈的特点及共享内存、独立内存栈的实际问题，我有一个新的思路，或许既能解决内存资源浪费，又能解决切换开销大的问题：

共享地址空间栈：
共享地址空间栈与共享内存栈类似，保证了所有任务的栈空间绝对地址是不变的，多任务之间共享。怎么缓解任务切换时栈数据备份、恢复开销问题？答案是利用操作系统的分页内存管理机制，还可以进一步做到动态栈空间增配。

主要流程：
1. 协程系统初始化时，使用 mmap 系统调用“占用”一块连续的虚拟地址空间，称为“共享栈区”，大小比如 8MB。访问权限设置为 PROT_NONE。
2. 协程任务结构中有一个“栈页数组”，项数最高可以容纳 8MB，任务创建时数据全部清 0。
3. 协程任务切换时，将“共享栈区”整体 munmap，并遍历新任务的“栈页数组”，将非 0 项全部 mmap 至 ”共享栈区“ 对应偏移处，权限为 PROT_READ | PORT_WRTIE，必要的情况下允许执行，完成栈切换。
4. 协程任务执行时，当产生对栈的读写访问时，产生段错误，触发 SIGSEGV，在信号处理函数中，从“栈页分配器”中分配一页栈页，先放入当前任务的“栈页数组”中，再 mmap 至 “共享栈区” 对应偏移处，完成栈空间动态增配。

**Comment by hnwyllmm** [comment]
楼主的主题是栈比较小的时候用共享栈，比较大的时候用独立栈？

**Comment by heiher** [comment]
@hnwyllmm 差不多，这样做或许比较好。

**Comment by walkerlala** [comment]
共享内存栈真的能节省内存资源？我看未必：无论是否共享，每个协程都需要一块自己的内存空间去做备份，因此，共享内存栈如何能节省内存资源呢？

**Comment by heiher** [comment]
@walkerlala 独立栈相对浪费内存要原因是任务多数情况下栈使用量较少，但存在突发很多的情况，比如调用的某个库函数分配了很大的局部数组，因此如果不支持动态栈增长，任务创建时又只分配了较小的栈空间，就存在越界风险，而如果只为少数的突发情况分配很大的栈空间，浪费就产生了。共享内存栈的协程任务结构中用于备份栈的空间是动态分配的，备份的大小也是任务此刻对栈的实际用量。

首先，SIGSEGV 在多线程情况下，系统是将其发送给产生这个异常的线程的，不会错误路由。其次，如果不可靠也不要紧，因为信号处理返回后还会回到之前的上下文继续执行，那么之前对栈空间的访问会重发，只有两种结果：如果已经 mmap 处理，访问得以继续，否则重新产生 SIGSEGV。最后，总有一次是会处理的。

**Comment by walkerlala** [comment]
On Sat, Mar 10, 2018 at 02:46:53AM +0000, Heiher wrote:
>  @walkerlala 独立栈相对浪费内存要原因是任务多数情况下栈使用量较少，但存在突发很多的情况，比如调用的某个库函数分配了很大的局部数组，因此如果不支持动态栈增长，任务创建时又只分配了较小的栈空间，就存在越界风险，而如果只为少数的突发情况分配很大的栈空间，浪费就产生了。共享内存栈的协程任务结构中用于备份栈的空间是动态分配的，备份的大小也是任务此刻对栈的实际用量。

clear.
 
> 首先，SIGSEGV 在多线程情况下，系统是将其发送给产生这个异常的线程的，不会错误路由。其次，如果不可靠也不要紧，因为信号处理返回后还会回到之前的上下文继续执行，那么之前对栈空间的访问会重发，只有两种结果：如果已经 mmap 处理，访问得以继续，否则重新产生 SIGSEGV。最后，总有一次是会处理的。

这个说得不正确，signal是per-process的。see: <http://man7.org/linux/man-pages/man7/signal.7.html>, and search for:

> The signal disposition is a per-process attribute: in a multithreaded application, the disposition of a particular signal is the same for all threads

**Comment by heiher** [comment]
@walkerlala 
A signal may be generated (and thus pending) for a process as a whole
       (e.g., when sent using kill(2)) or for a specific thread (e.g.,
       certain signals, such as SIGSEGV and SIGFPE, generated as a
       consequence of executing a specific machine-language instruction are
       thread directed, as are signals targeted at a specific thread using
       pthread_kill(3)). 

see: http://man7.org/linux/man-pages/man7/signal.7.html

**Comment by walkerlala** [comment]
On Sat, Mar 10, 2018 at 05:13:27AM +0000, Heiher wrote:
> @walkerlala 
> A signal may be generated (and thus pending) for a process as a whole
>        (e.g., when sent using kill(2)) or for a specific thread (e.g.,
>        certain signals, such as SIGSEGV and SIGFPE, generated as a
>        consequence of executing a specific machine-language instruction are
>        thread directed, as are signals targeted at a specific thread using
>        pthread_kill(3)). 

pthread_kill(3) 使用的是哪一个system call以使得可以将signal发给特定的thread？ 我印象中是没有这个system call的

**Comment by walkerlala** [comment]
On Sun, Mar 11, 2018 at 12:09:13AM +0800, Yubin Ruan wrote:
> On Sat, Mar 10, 2018 at 05:13:27AM +0000, Heiher wrote:
> > @walkerlala 
> > A signal may be generated (and thus pending) for a process as a whole
> >        (e.g., when sent using kill(2)) or for a specific thread (e.g.,
> >        certain signals, such as SIGSEGV and SIGFPE, generated as a
> >        consequence of executing a specific machine-language instruction are
> >        thread directed, as are signals targeted at a specific thread using
> >        pthread_kill(3)). 
> 
> pthread_kill(3) 使用的是哪一个system call以使得可以将signal发给特定的thread？ 我印象中是没有这个system call的

hmm...glibc的代码很多自动生成的东西: https://code.woboq.org/userspace/glibc/nptl/pthread_kill.c.html

至今还是没能将生成后的代码弄出来。有人会弄？

**Comment by heiher** [comment]
@walkerlala 

pthread_kill 在 Linux 平台是使用 tgkill 系统调用实现的， see: https://github.com/loongson-community/glibc/blob/glibc-2.26/sysdeps/unix/sysv/linux/pthread_kill.c

**Comment by walkerlala** [comment]
On Sun, Mar 11, 2018 at 01:44:13AM +0000, Heiher wrote:
> @walkerlala 
> 
> pthread_kill 在 Linux 平台是使用 tgkill 系统调用实现的， see: https://github.com/loongson-community/glibc/blob/glibc-2.26/sysdeps/unix/sysv/linux/pthread_kill.c

谢谢！

**Comment by heiher** [comment]
如果完全使用共享地址空间栈方式，协程任务的最小分配栈空间实际上是一个系统页大小，对于一个页大小都觉得太多的话，可以允许在创建任务时指定栈大小，对于指定栈大小的任务，从堆空间分配栈，绕过动态 mmap 机制。

**Comment by heiher** [comment]
共享地址空间栈初步实现：https://github.com/heiher/hev-task-system/commits/devel

**Comment by heiher** [comment]
引入了两点优化：
1. 同一任务调度切换时不刷共享栈区。
2. 增加多路共享栈区，循环分配给不同任务，使用不同路共享栈区的任务间切换互不影响。

**Comment by yuanzhubi** [comment]
@heiher 
On Sat, Mar 10, 2018 at 02:46:53AM +0000, Heiher wrote:
  @walkerlala 独立栈相对浪费内存要原因是任务多数情况下栈使用量较少，但存在突发很多的情况，比如调用的某个库函数分配了很大的局部数组，因此如果不支持动态栈增长，任务创建时又只分配了较小的栈空间，就存在越界风险，而如果只为少数的突发情况分配很大的栈空间，浪费就产生了。共享内存栈的协程任务结构中用于备份栈的空间是动态分配的，备份的大小也是任务此刻对栈的实际用量。


https://github.com/yuanzhubi/call_in_stack 这个库来解决你这个问题，只要不导致协程切换，所有的函数调用都可以call_in_stack一个全局变量来解决。

**Comment by heiher** [comment]
@yuanzhubi 你提供的是一种独立栈的实现方式吧？

**Comment by yuanzhubi** [comment]
@heiher 大部分函数根本不会导致协程切换（类似于内核多数中断处理代码，大部分流程中都会屏蔽响应新的中断一样）。所以对于这部分“安全函数“”的调用，可以使用call_in_stack 来调用这个函数，让他以一个线程局部的全局缓冲区为栈即可。
char buf[1024*1024];
void func(){
   call_in_stack(buf, printf, "Hello world!\n"); 
}
这样func 就不会发生栈溢出了（我的glibc，printf大约要消耗3K+的栈，所以有时候协程库里用fprintf来打印日志还是很危险的），call_in_stack 只会消耗参数拷贝(如果ABI是用寄存器传参的，则不会开销内存)和函数调用所需要的堆栈内存。

**Comment by heiher** [comment]
@yuanzhubi 我的理解这是一种分段式栈扩展方式，编写协程任务代码时如果认为将被调用的子函数可能需要较大的栈空间时，即临时切换至新分配的栈空间调用该子函数，子函数返回时再回收。

为了不浪费内存，我们需要避免的是协程任务处于等待状态时仍然持有较大的栈空间，所以调用链中可能导致任务进入等待态的子函数要避免用临时大空间栈来调用。

在实际的编程中就需要确认这两件事：
 1. 需要分析子函数最大需要多大的栈空间。
 2. 需要确认子函数内部调用链中不会导致任务切换。

感觉哪一个都不那么方便 :)

**Comment by heiher** [comment]
@yuanzhubi 

后来我又以一个实际案例来思考如何将 call in stack 应用上，源代码：
https://github.com/heiher/hev-task-system/blob/master/apps/curl.c

案例中是为每个下载任务创建了一个协程，协程中调用第三方库 libcurl 实现 http 下载，具体是使用了 curl_easy 同步阻塞模式，为了配合协程，重载了 poll 函数，重载的 poll 函数中 hev_task_sleep 和 hev_task_sleep 会使当前协程任务进入等待状态并进行任务切换。

假设 curl_easy_perform 可能会导致当前任务栈栈溢出，但又不能修改第三方 libcurl 库代码的情况下，怎样能用上 call in stack 呢？如果有好的方法，望分享 :)

**Comment by yuanzhubi** [comment]
@heiher 
https://github.com/yuanzhubi/cort_proto/blob/322dca5ce556ea4e06ab7e33bacc124cbb238255/pressure_test/cort_hook_libcurl_test.cpp#L60

curl_easy_perform 消耗堆栈不多，而且可控，可以让他使用协程堆栈。

其他的参数准备，结果处理的这些代码则不会导致协程切换可以call_in_stack。

注意是让你当前线程的所有不会导致协程切换的函数都使用call_in_stack **同一个线程局部的全局缓冲区**，所以你把他弄个1M都不怕，一个线程就1个嘛（不会导致协程切换的函数用call_in_stack共享栈，会导致协程切换的函数则用协程栈）。

**Comment by yuanzhubi** [comment]
“@yuanzhubi 我的理解这是一种分段式栈扩展方式，编写协程任务代码时如果认为将被调用的子函数可能需要较大的栈空间时，即临时切换至新分配的栈空间调用该子函数，子函数返回时再回收。”
@heiher 其实不是分多段栈，而是2个栈。 不会导致协程切换的函数共用一个栈（可能有递归，不定参数处理之类的，堆栈消耗比较多），会导致协程切换的函数则用所在协程的栈（或者说叫协程局部的堆栈，这些函数应该不要让他们做太多逻辑，尽量让堆栈消耗量比较固定，这样就可以精确的分配一个较小的协程栈大小来用）。

**Comment by heiher** [comment]
@yuanzhubi 

> https://github.com/yuanzhubi/cort_proto/blob/322dca5ce556ea4e06ab7e33bacc124cbb238255/pressure_test/cort_hook_libcurl_test.cpp#L60

> curl_easy_perform 消耗堆栈不多，而且可控，可以让他使用协程堆栈。

>其他的参数准备，结果处理的这些代码则不会导致协程切换可以call_in_stack。

> 注意是让你当前线程的所有不会导致协程切换的函数都使用call_in_stack 同一个线程局部的全局缓冲区，所以你把他弄个1M都不怕，一个线程就1个嘛（不会导致协程切换的函数用call_in_stack共享栈，会导致协程切换的函数则用协程栈）。

其实我举 curl_easy_perform 这个例子只是想说类似的情况，是假定： curl_easy_perform 确实需用大量的栈，且由于它是第三方代码，不能随意的修改实现（比如已经预编译了），而且在 curl_easy_perform 进去之后还确定会导致当前协程睡眠（它会调用 poll，而 poll 被 hook 了）。

如果用 call_in_stack 来调用 curl_easy_perform，必然需要先分配一个较大的栈，但又在 curl_easy_perform 没有返回前协程睡眠了，所以栈又不能释放，这就造成了协程任务睡眠时仍持有大空间的栈的情况。

总之，就是以一个实际的案例来思考同类问题如何更好的解决？

**Comment by yuanzhubi** [comment]
@heiher  这个时候你就根据实际情况来决定了。
如果你是在协程执行之后才发现自己需要调用curl_easy_perform（可能调用也可能不调用，协程执行之前不知道），但是协程创建时已经设置了一个较小的堆栈大小了（默认按照不会调用来设置的，可能协程里只有很少的情况才调用curl_easy_perform）。 这时候你可以选择new 一个缓冲区，然后call_in_stack  curl_easy_perform来避免栈溢出（相当于在协程栈上再创建了一个临时的分段栈）。

综上，上面这种实际情况下会有3个栈。
1. **全局栈（就是你说的大栈）**：每个线程只有一个，不会导致协程切换的函数Y都可以用这个栈来执行。 **注意不需要释放，除非线程结束**。
2. **协程栈**：每个协程创建时分配的，协程入口函数就在这个栈上执行。适合给可能发生协程切换的函数X执行（这是默认的函数调用方式，无需call_in_stack）。 注意在X中 如果调用了一个不会发生协程切换的函数Y，依然可以call_in_stack Y在全局栈上执行。
3. **伴随栈**：协程可能调用可能发生协程切换的函数Z 而且他可能消耗很大的栈而导致协程栈溢出。此时可以new 一份大内存作为一个伴随栈，在这个栈call_in_stack Z来执行。Z返回后可以不着急马上回收伴随栈，因为说不定还有下一个Z1会需要调用，可以在协程函数结束之后回收。也可以用池的方法进行管理。

以上策略实际在内核中断处理的驱动中也用得上：内核中断处理栈就4K或者8K，有时候遇到一些情况真的很麻烦。

**Comment by heiher** [comment]
@yuanzhubi 

原来我们的出发点不同，看上去侧重点也不同：
你的侧重点应该是：**任务创建时按最小需求分配栈，在任务执行中又能处理突发的较大需求，避免栈溢出问题。**

而我的侧重点是：**任务运行时持有满足任务实现最大需求的栈空间，任务睡眠时尽可能释放未使用（无有效数据）的栈空间。以避免一个线程中大量并发协程任务（任务数N），有N-1个协程任务处于等待状态，但仍然持有大容量的栈空间并且绝大部分栈空间还并未使用的怀具情况。**

**Comment by yuanzhubi** [comment]
"...而我的侧重点是：任务运行时持有满足任务实现最大需求的栈空间，任务睡眠时尽可能释放未使用（无有效数据）的栈空间。以避免一个线程中大量并发协程任务（任务数N），有N-1个协程任务处于等待状态，但仍然持有大容量的栈空间并且绝大部分栈空间还并未使用的怀具情况。"

@heiher 
我觉得你这个调度策略得考虑下性能喔。 我上面的策略在节省空间的同时几乎不带来什么时间开销。 侵入性也蛮小的，就是把有协程切换和没有协程切换的函数的逻辑分离就很好搞了（最好让协程切换的入逻辑尽量放协程入口函数去触发）。

**Comment by heiher** [comment]
@yuanzhubi 

> 把有协程切换和没有协程切换的函数的逻辑分离就很好搞了（最好让协程切换的入逻辑尽量放协程入口函数去触发）。

你不觉得这个在实际的业务代码中很难做到吗？如像上面我提到的 curl 的例子，对于业务中就是随时进行 I/O 操作的情况，怎么能设计得尽可能在入口函数时才触发调度呢？我们用协程不就是处理I/O密集型的应用时期望既能高并发，又能尽可能更自然的写业务逻辑，不用闭包、回调等需要携带上下文数据的方式吗？额外的要求越多，也就增加了对现有同步、阻塞式业务代码进行协程化改造的难度。个人认为栈扩展的方法是不错的，但就具体的应用来说，编程中有点难以操作。

**Comment by yuanzhubi** [comment]
"你不觉得这个在实际的业务代码中很难做到吗"
如果不care内存开销，那么把可以使用全局栈的临时数据也在局部栈上分配和使用就行了。 
我纯粹是为了给你做协程优化， 以为“...现有同步、阻塞式业务代码进行协程化改造”这种工作早就完成了（这libco不就是干这种事的么。。），当前的工作应该是减少内存开销。

**Comment by heiher** [comment]
@yuanzhubi 
作为一种优化方案还是不错的，更期待能有一种通用的解决方案。

> 我觉得你这个调度策略得考虑下性能喔。
你是指使用共享地址空间栈吧，的确，引入用户态、内核态切换越多，对单位时间内的调度切换次数影响都大。在我的 i7 硬件上实测发现，引入的 mmap/munmap 等系统调用消耗的时间与 memcpy 复制100多KB的数据差不多。

这种共享地址空间栈方式不需要修改业务代码来配合，兼容性较好。但在调度效率方面会有一些损失，相对 memcpy 备份栈的方式，应该可以找出一个栈空间使用临界点，小于这个点效率是低于它的，高于这个点效率能高于它。

为了减少栈切换开销，也可以做一些优化，已经实现的：
- 多路共享栈空间。
- 预映射最后使用的栈“页“（帧）。

未实现的：
- 动态评测临时点，低于这个点用 memcpy 备份，高于这个点用 mmap。

其实还是一个时间和空间的权衡吧，总之，就是任务运行时栈能动态增长不溢出，又能有办法在任务挂起时能够释放栈中未使用的部分空间。

欢迎吐槽，期待改进思路 :)

**Comment by yuanzhubi** [comment]
@heiher  关于扩增栈的问题，libgo有实践，而且跨平台的。
https://github.com/yyzybb537/libgo/tree/master/libgo

**Comment by heiher** [comment]
@yuanzhubi 

如果是能够重新设计语言或ABI，采用 call in stack 方式应该很容易就能解决我关注的问题点：
首先采用 call in stack 这类的方法为每级函数调用都指定新的栈空间。
其次新指定的栈空间都是调用时（前）从动态内存管理器分配的、函数返回时（后）释放。

这样栈既能动态增长，又不存在挂起时浪费，但在目前C/C++语言及ABI已经确定的情况下，看上去实现不了。或许这也是 go 等原生支持协程的语言的一个优势吧。

**Comment by yyzybb537** [comment]
os提供了“虚拟内存机制”

**Comment by heiher** [comment]
@yyzybb537 

你应该是想说内核提供了“虚拟内存”机制了，为什么还让多任务栈共享同一段虚拟地址空间，而不是每个任务 mmap 独立的虚拟地址？
主要原因：进程的虚拟地址空间不足，限制了任务并发数。比如32位虚拟地址空间系统，去掉内核空间后用户空间并不大。

本质上也还是避免协程任务挂起时仍然占用内存空间问题，用 malloc 分配是虚拟、物理地址空间都占，用 mmap 直接分配就是物理可以不占、虚拟还得占。多任务共享相同虚拟地址空间栈，既能挂起时虚拟、物理空间都不多占，又能避免进程可用虚拟地址空间不足问题。

或许我们可以在这基础上优化一下“多路共享地址空间栈”的初始化策略，对于地址空间很大64位，提高路数；而32位则保守一点。

**Comment by hnwyllmm** [comment]
@heiher "用 malloc 分配是虚拟、物理地址空间都占"
这个malloc不向分配的内存写入数据，也不会分配物理内存。物理内存是在第一次触发页错误时分配的。这与mmap匿名页一样的。
另外你说的memcpy与mmap的临界点，这个对不同的机器应该差别比较大。不止是与CPU相关，与内存和主板频率也有关系。而且，生产上一般不会用i7处理器，会用更稳定的企业版专用处理器(最少我们公司这样的)。我的意思就是如果使用这种方法，还需要有一个选择临界点的方法，而不是直接在编译时设定。

**Comment by hnwyllmm** [comment]
malloc不读写数据也不会触发页错误分配物理内存，与mmap表现一致。

**Comment by heiher** [comment]
@hnwyllmm 
malloc 我是这么理解的，Linux 系统上 malloc 分配的内存空间在系统层内存管理中也是按页映射的，但用户空间可能还有一层内存管理，具体的实现应该是影响背后的物理页映射情况的，比如元数据的写入、用户空间层面的回收与再分配等。

memcpy 与 mmap 等系统调用开销临界点的选取是与硬件平台的配置、系统综合负载等都相关的，初步的方法是期望通过动态训练获得。

**Comment by huanghantao** [comment]
> 引入的 mmap/munmap

你好，请问你现在测试这个临界点的做法是什么呢？

**Comment by huanghantao** [comment]
> @yuanzhubi
> 作为一种优化方案还是不错的，更期待能有一种通用的解决方案。
> 
> > 我觉得你这个调度策略得考虑下性能喔。
> 
> 你是指使用共享地址空间栈吧，的确，引入用户态、内核态切换越多，对单位时间内的调度切换次数影响都大。在我的 i7 硬件上实测发现，引入的 mmap/munmap 等系统调用消耗的时间与 memcpy 复制100多KB的数据差不多。
> 
> 这种共享地址空间栈方式不需要修改业务代码来配合，兼容性较好。但在调度效率方面会有一些损失，相对 memcpy 备份栈的方式，应该可以找出一个栈空间使用临界点，小于这个点效率是低于它的，高于这个点效率能高于它。
> 
> 为了减少栈切换开销，也可以做一些优化，已经实现的：
> 
> * 多路共享栈空间。
> * 预映射最后使用的栈“页“（帧）。
> 
> 未实现的：
> 
> * 动态评测临时点，低于这个点用 memcpy 备份，高于这个点用 mmap。
> 
> 其实还是一个时间和空间的权衡吧，总之，就是任务运行时栈能动态增长不溢出，又能有办法在任务挂起时能够释放栈中未使用的部分空间。
> 
> 欢迎吐槽，期待改进思路 :)

你好，请问你现在测试这个临界点的做法是什么呢？

**Comment by heiher** [comment]
@yyzybb537
> os提供了“虚拟内存机制”

嗯，最初我是简单的直接使用mmap来分配匿名页空间作为协程任务的栈，正好可以利用OS的虚拟内存机制延迟分配物理页，达到栈动态增长、动态分配。这个方法也是有缺陷的：
1. 栈空间的上限还是绑定了静态分配的虚拟地址空间上限，增长方向不能有占用。而且32位进程虚拟地址空间太小，限制了任务数量。
1. mmap映射的元数据开销也不低。

**Comment by yyzybb537** [comment]
@heiher 

已经9102年了，还提32位的server算是抬杠了吧？

**Comment by yyzybb537** [comment]
无需mmap，直接malloc即可，元信息的开销相比于KB级别的栈空间可以忽略不计了

**Comment by heiher** [comment]
@yyzybb537 
哈哈，回完才发现之前已经回复过了。

我是说印象中mmap的元数据开销是比较大的，malloc还好。现在的实现还是malloc分配栈，没能支持动态增长。
如果是连续栈空间动态增长，无非就是：
1. 为栈预留连续的虚拟地址空间。
1. 延迟分配对应物理地址空间。

libgo 目前是如何做的呢？

**Comment by yyzybb537** [comment]
直接malloc即可

**Comment by heiher** [comment]
@huanghantao 

简单来说就是在初始化阶段测试平台运行环境上执行mmap/munmap的时间开销约等于同多少字节的memcpy来确定一个阈值，低于的即用memcpy备份栈；否则用mmap/munmap调整映射关系(zero copy)。

**Comment by heiher** [comment]
@yyzybb537 

栈动态增长如何支持？

**Comment by hobby** [comment]
哩噶来件已经被我收埋佐啦哈哈 ^ ^
