### ISSUE TITLE
存在内在泄漏问题

### ISSUE THREAD

**Issue by s97712** [Tencent/libco#9]
不管是通过在协程中返回 或调用co_free,co_release都会泄漏内存，协程退出后并不会释放协程的独享栈，栈拷贝和其他资源

**Comment by wechatsunny** [comment]
libco的确不考虑完整的回收一个co，也就是不建议回收任何co。
类似线程__thread,协程里面__routine的存在也同样是暗示了这个选择。
使用协程时候统一用协程池的形式，避免各种资源残留 -- 实际上大家在使用线程的时候，也基本上是遵循这个规则

**Comment by s97712** [comment]
好吧 不过也有需要关闭协程的需求  已经改成协程返回自动释放资源了

**Comment by ralgond** [comment]
> 好吧 不过也有需要关闭协程的需求 已经改成协程返回自动释放资源了

请问您是如何做到协程返回就自动释放资源的，谢谢！
