### ISSUE TITLE
想问一下为什么这里要将函数返回地址保存起来呢？

### ISSUE THREAD

**Issue by asdf1352** [Tencent/libco#91]
https://github.com/Tencent/libco/blob/8ce6dfef26ccf6a1ecb55336dde18a6526f76666/coctx_swap.S#L51
对这一处不太明白，既然每一个协程都有自己的栈帧，函数返回地址又是保存在栈帧中的，不同于共享的寄存器，栈是相互独立的，为什么这里还要把返回地址压栈？，比如说我考虑成
`

#if defined(__i386__)
	leal %esp, %eax //sp 
	movl 4(%esp), %esp 
	leal 32(%esp), %esp //parm a : &regs[7] + sizeof(void*)

	pushl %eax //esp ->parm a 

	pushl %ebp
	pushl %esi
	pushl %edi
	pushl %edx
	pushl %ecx
	pushl %ebx

	
	movl 8(%eax), %esp //parm b -> &regs[0]

	popl %ebx  
	popl %ecx
	popl %edx
	popl %edi
	popl %esi
	popl %ebp
	popl %esp

	xorl %eax, %eax
	ret
`
这样会有什么问题呢？

**Comment by hnes** [comment]
当然可以这样做，你甚至可以将所有寄存器统统保存在栈帧上，只要注意好细节处理就可以。

不过我没有仔细看你的汇编代码，不能保证里面细节没有问题。

另外需要注意的是，SP是不应该用来直接寻址堆中的数据结构的。（原因请参加bug报告 [issue 90](https://github.com/Tencent/libco/issues/90)）

如果你想要实现自己的协程，建议参考[libaco](https://github.com/hnes/libaco)的[acosw](https://github.com/hnes/libaco/blob/master/acosw.S)（更快速且正确的）实现，腾讯的这个coctx_swap里面有bug而且效率低，更关键的是现在他们对这个项目似乎一点也不关心了。

**Comment by hnes** [comment]
[libaco](https://github.com/hnes/libaco)的README文档包含了完整的协程实现的方法论和严格的数学证明，如果你不喜欢读英文的话，它的中文文档过几天就会放出来。

另外，boost的[context](https://github.com/boostorg/context/blob/develop/src/asm/ontop_i386_sysv_elf_gas.S)库的协程实现也很棒，它就是把所有寄存器的状态统统保存在栈帧上，如果感兴趣的话你也可以看一下。

**Comment by hnes** [comment]
@asdf1352  不用客气，有问题的话欢迎继续交流 :)

**Comment by yuanzhubi** [comment]
libco需要实现拷贝栈，然而在协程切换之前，需要拷贝保存的内容到底有多长是不知道的。所以必须在栈切换的时候保存好栈指针前面的所有内容。

**Comment by asdf1352** [comment]
@yuanzhubi 原来如此，只在看独立栈没看拷贝栈的情况，谢谢大佬
