### ISSUE TITLE
A problem in share stack

### ISSUE THREAD

**Issue by lancewz** [Tencent/libco#97]
co_free function need set occupy_co = NULL in share stack.
like this:
void co_free( stCoRoutine_t *co )
{
    if (!co->cIsShareStack) 
    {    
        free(co->stack_mem->stack_buffer);
        free(co->stack_mem);
    } else {
                /* set NULL here */
		if (co->stack_mem->occupy_co == co) {
			co->stack_mem->occupy_co = NULL;
		}
	}
    free( co );
}

**Comment by Ananfa** [comment]
这里是有bug，不过这样改还没改全
https://github.com/Tencent/libco/issues/63
