### ISSUE TITLE
libco可以跟openssl结合使用吗？

### ISSUE THREAD

**Issue by lvmengkeji** [Tencent/libco#98]
比如实现一个https服务器

**Comment by leiffyli** [comment]
一般情况下是没有问题的，ssl绝大大部分api（ ssl_read, ssl_write等）都可以使用libco达到异执行的效果；

但是有些api，比如SSL_CTX_new() 这类接口，它最终可能会调用到poll接口等待/dev/random文件可读。因此在协程上执行这类函数可能会触发协程切换。业务如果加锁调用这类函数就可能因为协程切换而导致锁重入。

对于加锁调用ssl相关接口的场景，可以在调用前与调用后通过co_disable_hook_sys() 与 co_enable_hook_sys() 这两个api暂时取消与重新启用协程hook功能。

**Comment by lvmengkeji** [comment]
@leiffyli 谢谢，你们在项目中用过libco+openssl吗？openssl的api还是挺多坑的

**Comment by leiffyli** [comment]
@lvmengkeji 有的，我们线上有挺多ssl|+libco的服务调用。一般情况下避免持锁调用SSL就行，使用上没有太多需要修改的地方。
